# Generated by Django 5.0.6 on 2024-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Placed_student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="photo/%Y/%m/%d/")),
                ("designation", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
    ]
