# Generated by Django 5.0.6 on 2024-08-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("placement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placed_student",
            name="name",
            field=models.CharField(default="default_name", max_length=255),
        ),
    ]
