# Generated by Django 5.0.6 on 2024-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('reg_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('perctange', models.FloatField()),
                ('course', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
            ],
        ),
    ]
