# Generated by Django 5.0.6 on 2024-07-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_details_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='perctange',
            new_name='percentage',
        ),
    ]
